/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymnastique.du.cerveau;

/**
 *
 * @author asus 2014
 */
public class PageMemory extends javax.swing.JFrame {

    /**
     * Creates new form PageMemory
     */
    public PageMemory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_XO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_XO1 = new javax.swing.JButton();
        btn_go_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_XO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/Logo mastermind.jpeg"))); // NOI18N
        btn_XO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XOActionPerformed(evt);
            }
        });
        getContentPane().add(btn_XO, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 159, 140, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/Memory.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 0, -1, 107));

        btn_XO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/logo taquin.jpg"))); // NOI18N
        btn_XO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XO1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_XO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 309, 140, 140));

        btn_go_back.setBackground(new java.awt.Color(204, 204, 204));
        btn_go_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/btn go back.png"))); // NOI18N
        btn_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_go_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XOActionPerformed
        // TODO add your handling code here:
         //this.setVisible(false);
            MasterMindFenetre1 g = new MasterMindFenetre1();
           
            g.setVisible(true);
        

    }//GEN-LAST:event_btn_XOActionPerformed

    private void btn_XO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XO1ActionPerformed
        // TODO add your handling code here:
        Jouer j =new Jouer();
                j.setVisible(true);
    }//GEN-LAST:event_btn_XO1ActionPerformed

    private void btn_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_backActionPerformed
        this.setVisible(false);
        PageAccueil a1 = new PageAccueil();
        a1.setVisible(true);
    }//GEN-LAST:event_btn_go_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageMemory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_XO;
    private javax.swing.JButton btn_XO1;
    private javax.swing.JButton btn_go_back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
