/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymnastique.du.cerveau;

/**
 *
 * @author ASUS
 */
public class PageAccueil extends javax.swing.JFrame {

    /**
     * Creates new form PageAccueil
     */
    public PageAccueil() {
        initComponents();
        lbl_surname.setText("Hello "+Surname.surname+" !!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_go = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rad_ref = new javax.swing.JRadioButton();
        rad_memo = new javax.swing.JRadioButton();
        red_strat = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_surname = new javax.swing.JLabel();
        btn_goo = new javax.swing.JButton();
        btn_go_back = new javax.swing.JButton();

        btn_go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/bouton-go.jpg"))); // NOI18N
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("What do you prefer?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 33));

        rad_ref.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rad_ref);
        rad_ref.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rad_ref.setText("Reflexion games");
        rad_ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_refActionPerformed(evt);
            }
        });
        jPanel1.add(rad_ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        rad_memo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rad_memo);
        rad_memo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rad_memo.setText("Memory games");
        jPanel1.add(rad_memo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        red_strat.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(red_strat);
        red_strat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        red_strat.setText("Strategy games");
        jPanel1.add(red_strat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/brain-fit.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 330, 230));

        lbl_surname.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_surname.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lbl_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 300, 50));

        btn_goo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/bouton-go.jpg"))); // NOI18N
        btn_goo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gooActionPerformed(evt);
            }
        });
        jPanel1.add(btn_goo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, 80));

        btn_go_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_go_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymnastique/du/cerveau/btn go back.png"))); // NOI18N
        btn_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_go_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rad_refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_refActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_rad_refActionPerformed

    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btn_goActionPerformed

    private void btn_gooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gooActionPerformed
     
        if (rad_ref.isSelected()==true){
          PageReflexion pr = new PageReflexion();
       this.setVisible(false);
       pr.setVisible(true);
        }
         if (rad_memo.isSelected()==true){
          PageMemory pr = new PageMemory();
       this.setVisible(false);
       pr.setVisible(true);
        }
          if (red_strat.isSelected()==true){
          PageStrategy pr = new PageStrategy();
       this.setVisible(false);
       pr.setVisible(true);
        }
    }//GEN-LAST:event_btn_gooActionPerformed

    private void btn_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_backActionPerformed
       this.setVisible(false);
       Authentification a1 = new Authentification();
       a1.setVisible(true);
    }//GEN-LAST:event_btn_go_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go;
    private javax.swing.JButton btn_go_back;
    private javax.swing.JButton btn_goo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JRadioButton rad_memo;
    private javax.swing.JRadioButton rad_ref;
    private javax.swing.JRadioButton red_strat;
    // End of variables declaration//GEN-END:variables
}
